In [5]:
import numpy as np

N, L = map(int, input().split())
print(N, L)

leaks = list(map(int, input().split()))
leaks = np.array(leaks)
print(leaks)

4 2
[  1   2 100 101]


In [17]:
first_tape_left_edge = leaks[0] - 0.5
first_tape_right_edge = first_tape_left_edge + L

print(first_tape_left_edge, first_tape_right_edge)

removals = leaks[leaks<=first_tape_right_edge]
print(removals)
num_removed = len(removals)
print(num_removed)

new_leaks = leaks[num_removed : ]
print(new_leaks)

0.5 2.5
[1 2]
2
[100 101]


In [ ]:
first_tape_left_edge = leaks[0] - 0.5
first_tape_right_edge = first_tape_left_edge + L

print(first_tape_left_edge, first_tape_right_edge)

removals = leaks[leaks<=first_tape_right_edge]
print(removals)
num_removed = len(removals)
print(num_removed)

new_leaks = leaks[num_removed : ]
print(new_leaks)

In [19]:
import numpy as np

N, L = map(int, input().split())
print(N, L)

leaks = np.array(list(map(int, input().split())))
print(leaks)

first_tape_right_edge = leaks[0] - 0.5 + L
leaks = leaks[leaks > first_tape_right_edge]
print(leaks)

4 2
[  1   2 100 101]
[100 101]


In [26]:
import numpy as np

N, L = map(int, input().split())
print(N, L)

leaks = np.array(list(map(int, input().split())))
leaks.sort()
print(leaks)
num_tapes = 0

while len(leaks) > 0:
    num_tapes += 1
    tape_right_edge = leaks[0] - 0.5 + L
    leaks = leaks[leaks > tape_right_edge]
    print(f"tape_right_edge : {tape_right_edge}, leaks : {leaks}")
    
print(num_tapes)

4 2
[  1   2 100 101]
tape_right_edge : 2.5, leaks : [100 101]
tape_right_edge : 101.5, leaks : []
2


In [33]:
import numpy as np

N, L = map(int, input().split())
print(N, L)

leaks = np.array(list(map(int, input().split())))
#print(leaks)

for i in leaks:
    print(i, end=" ")    
    
leaks.sort()
num_tapes = 0

while len(leaks) > 0:
    num_tapes += 1
    tape_right_edge = leaks[0] - 0.5 + L
    leaks = leaks[leaks > tape_right_edge]
    #print(f"tape_right_edge : {tape_right_edge}, leaks : {leaks}")

print()    
print(num_tapes)

4 2
1 2 100 101 
2


In [40]:
N, L = map(int, input().split())
print(N, L)

leaks = list(map(int, input().split()))
for i in leaks:
    print(i, end=' ')
print()

leaks.sort()
#print(leaks)
num_tapes = 0

while leaks:
    num_tapes += 1
    tape_right_edge = leaks[0] - 0.5 + L
    leaks = [leak for leak in leaks if leak > tape_right_edge ]

print(num_tapes)

3 1
3 2 1 
3


##### 좌표압축기법

In [8]:
N, L = map(int, input().split())
coord = list(map(int, input().split()))
coord.sort()
ans = 0 # ans는 사용된 테이프의 갯수

while coord:
    print(coord)
    x = coord[0]
    ans += 1
    coord = [c for c in coord if c >= x + L]
    print(f"coord : {coord}, x : {x}, ans : {ans}")
    
print()
print(ans)

[1, 2, 100, 101]
coord : [100, 101], x : 1, ans : 1
[100, 101]
coord : [], x : 100, ans : 2

2


In [16]:
expression = '(RU(b(i(n)))'
stack = []

for exp in expression:
    if exp == "(":
        stack.append(exp)
        
    elif exp == ")":
        if not stack.pop():
            print("False")
            
    print(f'exp : {exp}, stack : {stack}')

exp : (, stack : ['(']
exp : R, stack : ['(']
exp : U, stack : ['(']
exp : (, stack : ['(', '(']
exp : b, stack : ['(', '(']
exp : (, stack : ['(', '(', '(']
exp : i, stack : ['(', '(', '(']
exp : (, stack : ['(', '(', '(', '(']
exp : n, stack : ['(', '(', '(', '(']
exp : ), stack : ['(', '(', '(']
exp : ), stack : ['(', '(']
exp : ), stack : ['(']
